// Display strings
#pragma once

// ---------------------------------------------------------------
#ifdef DISPLAYLANGUAGE_DE

#define STR_IDLETIMEINSECONDS "Ruhezeit in Sekunden"
#define STR_SENSORTHRESHOLD "Sensorschwelle"
#define STR_LORAPACKET "LoRa-Paket"
#define STR_CONFIRMED "Zugestellt"
#define STR_SENT "Gesendet"
#define STR_VBATLOADER "Akku-/Ladespannung"
#define STR_EMPTY "Leer"
#define STR_FULL "Voll"
#define STR_DISPLAYMODE "Anzeigemodus"
#define STR_SERIALPRINTENABLED "Serial.print aktiv"
#define STR_FACTORYDEFAULT "Werkseinstellungen"
#define STR_SOUND "Sound"
#define STR_MINIMAL "Minimal"
#define STR_MAXIMAL "Maximal"
#define STR_ON "Ein"
#define STR_OFF "Aus"
#define STR_YES "Ja"
#define STR_NO "Nein"
#define STR_START "Start"
#define STR_BATTERY "Batterie"
#define STR_IDLETIME "Ruhezeit"
#define STR_THRESHOLD "Schwelle"
#define STR_DISPLAY "Display"
#define STR_SERIAL "Serial"
#define STR_LORATEST "LoRa-Test"
#define STR_INFO "Info"
#define STR_RESET "Reset"
#define STR_RESTART "Neustart"
#define STR_COULDNOTSTARTROTARYENCODER "Rotary Encoder konnte\nnicht gestartet\nwerden!"
#define STR_INIT "Init..."
#define STR_COULDNOTFINDLORA "LoRa-Modul\nnicht gefunden!"
#define STR_COULDNOTFINDMPU "MPU6050 nicht gefunden!"
#define STR_FIN "Fertig"

#endif

// ---------------------------------------------------------------
#ifdef DISPLAYLANGUAGE_EN

#define STR_IDLETIMEINSECONDS "Idle time in seconds"
#define STR_SENSORTHRESHOLD "Sensorthreshold"
#define STR_LORAPACKET "LoRa packet"
#define STR_CONFIRMED "Confirmed"
#define STR_SENT "Sent"
#define STR_VBATLOADER "Battery-/Loadvoltage"
#define STR_EMPTY "Empty"
#define STR_FULL "Full"
#define STR_DISPLAYMODE "Display mode"
#define STR_SERIALPRINTENABLED "Serial.print enabled"
#define STR_FACTORYDEFAULT "To factory default"
#define STR_SOUND "Sound"
#define STR_MINIMAL "Minimal"
#define STR_MAXIMAL "Maximal"
#define STR_ON "On"
#define STR_OFF "Off"
#define STR_YES "Yes"
#define STR_NO "No"
#define STR_START "Start"
#define STR_BATTERY "Battery"
#define STR_IDLETIME "Idle time"
#define STR_THRESHOLD "Theshold"
#define STR_DISPLAY "Display"
#define STR_SERIAL "Serial"
#define STR_LORATEST "LoRa test"
#define STR_INFO "Info"
#define STR_RESET "Reset"
#define STR_RESTART "Restart"
#define STR_COULDNOTSTARTROTARYENCODER "Could not start\nrotary encoder!"
#define STR_INIT "Init..."
#define STR_COULDNOTFINDLORA "LoRa modul\nnot found!"
#define STR_COULDNOTFINDMPU "MPU6050 not found!"
#define STR_FIN "Done"

#endif
